### ISSUE TITLE
Document how to use tdnf in the vic endpoint for debugging

### ISSUE THREAD

**Issue by corrieb** [vmware/vic-product#1058]
There are reasons why you might want to install a capability in the VIC endpoint VM that doesn't exist out of the box. An NFS client, for example, to test or debug connection to an NFS server. 

Currently, tdnf doesn't work in the endpoint VM without first running `rpm --rebuilddb`. This is confusing even our field who don't know about this magic @tschwaller.

We should document why you might want to install a dependency in an endpoint VM, how to do it and stress that whatever you do, it doesn't persist.

This links also to my request for us to create a validation image - https://github.com/vmware/vic/issues/6704. If we had this, the need for customers to add dependencies to the endpoint VM may well be diminished.

**Comment by mdubya66** [comment]
The error seen before doing the rpm --rebuilddb is 
```
root@ [ ~ ]# tdnf info
Error(1304) : Hawkey - I/O error
```

**Comment by tschwaller** [comment]
An example what to do if you want to mount a NFS share.

```
rpm --rebuilddb
tdnf --releasever 1.0 install nfs-utils
tdnf install iana-etc-2.30-2.ph1
ls -al /usr/sbin/mount.nfs
systemctl status rpcbind
mount -t nfs ...
```

The `iana-etc-2.30-2.ph1` package is needed to get the file `/etc/services` which is missing. I had to add `--releasever 1.0` to make the install command work, but I do not know if this is necessary in general. I also had to change the default Photon repo, since it was pointing to a wrong repo.

**Comment by corrieb** [comment]
Important to also note that `rpm --rebuilddb` gives you an unpopulated database so it doesn't know about existing packages. That means that if you install something, tdnf will try to install every other dependency into the endpoint VM, even if that dependency is already there.

**Comment by stuclem** [comment]
Enhancement, not new feature. Medium.

**Comment by stuclem** [comment]
Boosting priority to high following request from @pauldul and @tschwaller.

**Comment by stuclem** [comment]
First priority post-GA

**Comment by stuclem** [comment]
I'm finally getting around to documenting this. I am having a few problems getting it to work, particularly in relation to accessing the photon repos from the VCH, as @tschwaller mentions above. I have updated `/etc/yum.repos.d/photon-updates-local.repo` and `/etc/yum.repos.d/photon-local.repo` so that `baseurl` points to http://dl.bintray.com/vmware/photon_dev_x86_64/ (a hint that I saw in https://github.com/vmware/photon/issues/400), which worked to some extent but still isn't giving me any joy with the `tdnf install iana-etc-2.30-2.ph1` step. 

@tschwaller @corrieb, do you have any ideas? Thanks!

**Comment by stuclem** [comment]
More specific information:

1. The procedure I have written up [here](https://github.com/stuclem/vic-product/blob/tdnf/docs/user_doc/vic_vsphere_admin/vch_install_packages.md) works fine.
2. However, once you try to actuall install something by running `tdnf --releasever 1.0 install nfs-utils`, it fails, complaining that `/bin/sh`, `/sbin/ldconfig`, `/bin/bash` are missing, which they aren't. 

@tschwaller believes that this is because `rpm --rebuilddb` is not actually populating the DB and the Packages file is missing in `/var/lib/rpm`.

@corrieb do you know how we get the DB to populate?

**Comment by stuclem** [comment]
Also, if I attempt to install `iana-etc-2.30-2.ph1`, which @tschwaller says is required, I get the following error:

```
root@ [ ~ ]# tdnf install iana-etc-2.30-2.ph1
Error(1013) : Packagelist was empty
```

**Comment by tschwaller** [comment]
The procedure which worked in the past does not seem to work anymore in VIC 1.3.0. I will open a new ticket for the missing `/var/lib/rpm/Packages` file

**Comment by stuclem** [comment]
See https://github.com/vmware/vic-product/issues/1350 for a workaround.

**Comment by stuclem** [comment]
Draft doc is available for review in PR https://github.com/vmware/vic-product/pull/1355.
