### ISSUE TITLE
Get  x-xenon-auth-token for automating addition of container hosts to Admiral

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1125]
@sergiosagu @andrewc-vmware @mhagen-vmware 

Currently for automating VCH addition I am using the x-xenon-auth-token from Admiral's browser login page.

![image](https://user-images.githubusercontent.com/25006749/33112767-e1e34850-cf7a-11e7-972c-10f769a83719.png)

and passing it to script to be able to add container hosts to Admiral.

This token keeps changing. Is there a way to get this token programatically without having to login to browser page?

**Comment by sergiosagu** [comment]
Currently there's no option to get it programmatically since it was (is) not part of the requirements. We can add it at some point or better to identify the scenarios that you want to automate and make sure that the Admiral CLI is compatible with them when in VIC mode. In this way you won't need to handle tokens manually but just rely on the Admiral CLI.

cc @martin-borisov @sbadem

**Comment by mdubya66** [comment]
Issue moved to [vmware/admiral #220](https://github.com/vmware/admiral/issues/220) via [**ZenHub**](https://www.zenhub.com/)
