### ISSUE TITLE
Repurpose the topic on registering with external PSC

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1162]
Per @andrewtchin in https://github.com/vmware/vic-product/pull/1141, the topic [vSphere Integrated Containers Appliance Fails to Register with PSC](https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/ts_register_psc_fails.html) is currently 1.2.0 specific and should be rephrased and retitled to "Manually Register the Appliance with the PSC".

**Comment by stuclem** [comment]
@andrewtchin and @anchal-agrawal - should this actually be an internal KB for use only by GSS? Under what circumstances would we want customers to try this? Surely if registration fails in the Web page, it will continue to fail in the workaround, now that external PSC is supported in the getting started page?

**Comment by stuclem** [comment]
Remove topic in short term, then repurpose post-GA.

**Comment by anchal-agrawal** [comment]
> Remove topic in short term, then repurpose post-GA.

I agree.

The current troubleshooting doc can be repurposed as a "Manually Register the Appliance with the PSC" like you said. Since 1.2.1, registration via the appliance Getting Started page allows users to configure the PSC instance FQDN and the PSC domain.

For VIC versions >= 1.2.1, the doc is helpful if customers want to customize other values that we supply for PSC registration. There are only 3 other such values at the moment (https://github.com/vmware/vic-product/blob/master/installer/fileserver/tasks.go#L107-L109):

* PSC username - currently obtained from the Getting Started page's login field for the vSphere username
* PSC password - currently obtained from the Getting Started page's login field for the vSphere password
* Admiral URL - currently obtained internally by using the static hostname if available, otherwise using the appliance IP

At this time, we haven't seen a case where the user would need to configure these values. However, I think the doc is a good resource as a general-purpose reference for manually registering with PSC. Re-purposing it as a KB can be considered, too.

**Comment by stuclem** [comment]
Thanks @anchal-agrawal. Indeed the need to be able to update the PSC password after deployment is pretty important. So, we should keep this in the docs. I will remove it from 1.3.0, then reinstate an updated version in a post-GA update. Leaving it in 1.3.0 for removal, and adding it to 1.3.0 post-GA doc update for repurposing and reinsertion.

**Comment by stuclem** [comment]
Removed the topic in PR #1292. As discussed with @anchal-agrawal, I will repurpose this topic and reinstate it in a post-GA update.
