### ISSUE TITLE
Document how to update image store

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#130]
Per https://github.com/vmware/vic/issues/4519.

**Comment by stuclem** [comment]
Not in 1.3.

**Comment by stuclem** [comment]
Not in 1.4.x

**Comment by zjs** [comment]
As noted in https://github.com/vmware/vic/issues/4519#issuecomment-435477261, our recommendation is to create a new VCH in order to switch to a different image store. We may wish to document this, along with the overall process (something like: create the new VCH with the new image store, re-pull images, re-deploy containers on new VCH over time).
