### ISSUE TITLE
Document how to remove HTML5 plugin

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#1423]
Slack user reported that this does not contain instructions on how to remove the H5 plugin https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/uninstall_vic.html
I'm not sure what the correct steps are, @jooskim @jak-atx should know them

**Comment by stuclem** [comment]
@andrewtchin actually, this procedure does include the steps to remove both of the plug-ins. Steps 4.iii is for the H5 plug-in and step 4.v is for the flex plug-in. @jooskim can confirm, and then I'll close this. Thanks!

**Comment by jooskim** [comment]
@stuclem yes you're correct, but i think the uninstall steps can be replaced with simply running the uninstall.sh or bat file just like when installing the plugin. Any reason you documented the method using MOB?

**Comment by stuclem** [comment]
@jooskim, @alextopuzov documented the MOB method because we think it's simpler. To run the script, you have to have the VIC engine package on the machine on which you're running the script. There's no guarantee that you will run `uninstall.sh`/`bat` on the same machine as you ran `install.sh`/`bat`. If you're using VCSA, there's no guarantee that you left the package on the appliance VM after you installed the plug-in. If you start downloading packages again to run the uninstall script, there's no guarantee that you'll download the same version as was used for installation. So, we decided that all of the steps involved in downloading the correct package, copying it to the VCSA, etc., were a lot more cumbersome than just unregistering the extensions directly in the MOB. After all, the MOB is a one-stop shop that is designed for this purpose, that allows you to uninstall both of the plug-ins in the same way, regardless of whether you are using VC on Windows or VCSA. If there is a technical reason why we should use the script rather than the MOB to unregister the plug-ins, then we'll document the script. But if not, then we think that the simpler MOB method is better.

**Comment by jooskim** [comment]
Plugin uninstallation script doesn't require that you have the matching version of the `vic-ui` binary whatsoever which means you can basically use any uninstaller script version to perform the uninstallation. It is just a wrapper script that calls the vic-ui binary which works exactly the same way as the vSphere Web Services API. That being said, I agree that using the MOB is a lot simpler for the user. Let's keep the MOB instructions.

**Comment by andrewtchin** [comment]
Oops sorry I didn't see that @stuclem thanks!

**Comment by stuclem** [comment]
OK, thanks @jooskim !
