### ISSUE TITLE
Allow access to PDF of documentation

### ISSUE THREAD

**Issue by JosephJackson** [vmware/vic-product#15]
The vic-product documentation looks great in a web browser, but can't be printed without a lot of trouble. Printing from Chrome, Firefox, or Safari results in a single page that captures what's visible on the screen without the remainder of the document above or below the current screenful. I'd like access to a PDF version that can be printed, read off-line, etc. It appears that GitBooks allows PDF generation, but it must be enabled on a per-book basis:

https://help.gitbook.com/books/how-can-i-provide-a-pdf-version-of-my-book.html

I'd love to see that enabled for all the VIC-related GitBook publications.

Joe Jackson,
Carnegie Mellon University.

**Comment by mreferre** [comment]
Thanks for the feedback @JosephJackson. 

@stuclem See above ^^^^^^^^

**Comment by stuclem** [comment]
Hi @JosephJackson, are you attempting to print the HTML versions? We do provide PDFs of the VIC Engine docs, that you can access here: https://vmware.github.io/vic-product/#getting-started

We don't yet have PDFs of the VIC Registry/Harbor docs, but these should be printable as, unlike the VIC Engine docs, they are just single pages rather than structured docs.

**Comment by JosephJackson** [comment]
Thanks for the pointer to the PDFs. That's exactly what I needed!

**Comment by stuclem** [comment]
OK, glad that sorted you out!
