### ISSUE TITLE
vSphere "Virtual Machine Snapshot Size" warnings for large images

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1587]
@corrieb commented on [Fri Oct 20 2017](https://github.com/vmware/vic/issues/6601)

At a customer site, they have a docker image with 46 layers that they downloaded and ran. The layers are nothing special - quite a few metadata layers etc. The image failed to deploy initially (could be related to #6600 - maybe the reason for the invalid state error?) and then they tried again and it deployed successfully. 

What's problematic is that after a certain number of snapshots, vSphere started sending out warnings about the Virtual Machine snapshot size (this is a warning on the endpoint VM that's populating the snapshots). It issued a warning for every new layer pulled and then **emailed the sysadmin for every single layer pulled!!**

According to the email, it's more about the absolute size of the image rather than the number of layers. The email stated that between 2GB - 4GB of snapshots, you get a yellow warning. Above 4GB you will get a red warning.

---

@corrieb commented on [Fri Oct 20 2017](https://github.com/vmware/vic/issues/6601#issuecomment-338232867)

I think the best thing we can do is to document how to reconfigure the warnings just for a particular cluster so that you can override them.

---

@stuclem commented on [Mon Oct 23 2017](https://github.com/vmware/vic/issues/6601#issuecomment-338656284)

@corrieb can you please provide details of the exact text of the warning? Thanks

---

@stuclem commented on [Thu Jan 11 2018](https://github.com/vmware/vic/issues/6601#issuecomment-356878990)

@corrieb @anchal-agrawal is this a purely doc issue, or is there a dev element? If it's purely doc, we should move it to `vic-product`.

---

@anchal-agrawal commented on [Thu Jan 11 2018](https://github.com/vmware/vic/issues/6601#issuecomment-356902441)

I'm not sure - deferring to @corrieb.

---

@stuclem commented on [Thu Apr 12 2018](https://github.com/vmware/vic/issues/6601#issuecomment-380718806)

Moving to vic-product for doc

**Comment by stuclem** [comment]
@zjs is this still an issue?

**Comment by zjs** [comment]
I don't have any context on this beyond what's in https://github.com/vmware/vic-product/issues/1587#issue-313622395. However, I _suspect_ that this may be related to vSphere configuration around alerting related to memory usage, since we write images to a tmpfs directory. If memory usage alerts are enabled (or inherited) on the endpoint VM and we download a large enough VMDK, it seems likely that we could use enough of the endpoint VM's memory that we trigger a "90% memory usage" alert or similar.

I'm not exactly sure how we would want to document this.

We kind of hint at the idea that image layers are written to the endpoint VM's memory here. Perhaps that just needs to be made more explicit: https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/vch_compute.html#endpointmemory (If it's clear that the image layers are stored in memory during `docker pull`, it may be clear that you don't want to have aggressive alerting on the endpoint VM's memory usage. Alternatively, maybe we want to spell that out.)

**Comment by stuclem** [comment]
Thanks @zjs, I'll add a note in that topic to this effect.

**Comment by stuclem** [comment]
@vidya-v can you please take a look at this one? Thanks!

**Comment by vidya-v** [comment]
Documented - PR [2334](https://github.com/vmware/vic-product/pull/2334)
