### ISSUE TITLE
VIC upgrade scenario breaks by Harbor DB changes(master)

### ISSUE THREAD

**Issue by wy65701436** [vmware/vic-product#1709]
As for harbor has migrated DB to pgsql, the migrator won't work for the master build, and it breaks the VIC upgrade test in nightly suite.

Harbor team will provide an new DB migrator, let's use this issue to track.

**Comment by mdharamadas1** [comment]
FYI, this is currently a blocker for night test suite as its impacting upgrade tests.

**Comment by sgairo** [comment]
@mdharamadas1 Do you feel comfortable giving it an estimate?

**Comment by mdharamadas1** [comment]
@sgairo I can't, probably @wy65701436 ?

**Comment by mdubya66** [comment]
making this a p0 since it's blocking successful nightlies.

**Comment by wy65701436** [comment]
@andrewtchin @morrisjason, please update the builder script to pick up harbor stable build from https://storage.googleapis.com/harbor-builds/master.stable, it holds the URL of gcr. 

Harbor team could make sure the build in the master.stable passed our full CI, and won't break the upgrade testing in nightly.

**Comment by morris-jason** [comment]
@reasonerjt wy65701436 I do not believe this is the correct approach.

This file links to `https://storage.googleapis.com/harbor-releases/release-1.5.0/harbor-offline-installer-v1.5.0.tgz`, but we expect it to link to the latest stable **master** build, ie `https://storage.googleapis.com/harbor-builds/harbor-offline-installer-v1.5.0-build.1234.tgz`

**Comment by reasonerjt** [comment]
@morris-jason,  thanks for pointing it out.

Currently the `master.stable` points to a 1.5 branch build because the upgrade master build, and we expect it points to build on master branch once we verified the upgrade.

hypothetically, if you wanna ship a 1.6 release tomorrow, you can package this 1.5 build of Harbor and nothing will break.

The idea is that we explicitly provide a Harbor build to tell you that **this is the build should be integrated**.

Are you suggesting the filename `master.stable` is misleading?  We may change it to `vic.master.stable` to indicate it's the build to be integrated with vic-product `master` branch, but it's a little trivial.

**Comment by morris-jason** [comment]
@reasonerjt my concerns that the stable file should contain a link to the harbor-builds bucket, not harbor-releases, is trivial. 

The overall concern here is that, because this is now a very manual process, the ova testing will occur on old versions of harbor if the stable file is not updated in a timely manner.

We need to garuntee that we are testing the most up to date version possible that is sill stable. In my opninion, if a feature is going to break master for a prolonged period of time, it should be done on a feature branch. That way we can still test the other changes going into harbor.

If the most recent stable version right now is 1.5.0 then that’s what we should include. But let’s ensure that we don’t get too far behind in the stable version that we run into problems close to a GA, RCs, etc.
