### ISSUE TITLE
Further improvements to certificate docs 

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1828]
From an internal bug filed by @dbarkelew:

The certificate process for VIC is very confusing currently. 

When using intermediate CAs it is unclear if chains are needed in the OVA wizard. I would expect just the signed VIC Appliance certificate in the management portal certificate input and a chain of the intermediate CAs and root CA in the CA field of the install wizard. 

Converting the certificates to the expected format for the management portal wasn't clear. I am thinking this needs a table for converting the following to the components needed. 
Starting -> how to break down to the componet
pksc#12 -> Leaf cert, CA Chain Certificate, Private key in PKCS#8 format
P7b -> Leaf Cert, Private key in PKCS#8 format
RSA/PKCS#1 -> Private key in PKCS#8 format

Then another table covering details required for the certificate for client authentication with the container management portal when adding a VCH. For example the customer found that a certificate did not have the correct key usage and had to be re-issued. Then struggled because container management portal needed RSA format for adding the VCH and was using PKCS#8 because that is what the ova wizard used. The certificate reference is not clear about these requirements. Have a third table discussing the VCH certificate and making sure to convert it properly also would be useful. The certificate reference does start this but is not complete.
https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/vic_cert_reference.html

What also might be useful is a one stop shop start to finish for certificates with VIC. The information seems scattered and customers are not connecting the dots between VCH, VIC Appliance and Client certificates for adding the VHC to the VIC Appliance or use with the docker-client.                   

bug2138800

**Comment by stuclem** [comment]
Moving this to In Progress as a lot of customers seem to be hitting issues with certs.

**Comment by stuclem** [comment]
@martin-borisov and @reasonerjt can you also please take a look at the diagram above?

**Comment by dbarkelew** [comment]
Good idea to diagram the certificates out. 

I could be missing some details, but if I am not mistaken the vSphere Integrated Containers Appliance Certificate is actually 4 different connections type that could be using a different certificate for each, typically the same one is reused but not always.
- Admiral cert port 8282 also seen by vCenter when authenticating at the sso login
- Harbor cert port 443 
- file-server cert port 9443 and I believe is seen by vCenter during initialization 
- Client certificate for adding the VCH and future task operations against the VCH.

That said I suspect there is a push to reduce this, however last time I replace a certificate for admiral, the file-server certificate did not update and had to be updated separately. 

It might be easier to visualize by starting from the network diagram and label each path. 

The Management portal to VCH is missing the certificate in the other direction that is used when adding the VCH to the management portal. These are client certs the users adds from the vic management portal > identity mangagement > credentials.

**Comment by stuclem** [comment]
@dbarkelew are you sure that the certs can be different? As of 1.4 (I think) you only configure one certificate for the appliance during deployment. The options to configure different certs for Management Portal, Registry, file server, etc. have been removed from the OVA wizard.

I don't think that I can fit four arrows between the appliance and VC into the diagram, so I have updated the blurb for the VC-appliance connection as follows:

"vCenter Server verifies vSphere Integrated Containers  appliance certificate to authenticate Management Portal, Registry, and file server during initialization"

For the MP to VCH connection, I have made the arrow double-ended.

**Comment by dbarkelew** [comment]
@stuclem I am not sure. Not only does deployment need to be looked at but certificate replacement after deployment will need to be looked at. Is there confirmation of what the expected behavior should be. 

I am under the impression each service is still considered different and having individual certificates for each is still supported. I seem to remember that the last certificate replacement I did only updated the certificate the Admiral service used.

**Comment by dbarkelew** [comment]
I did not know this diagram was planned to be used in the documentation page. I thought this was just a rough sketch diagram to look at certificates to write a table from or something.  https://github.com/vmware/vic-product/blob/66d17f5a0db6e082e83ad6e2d10c8c04d2b304e0/docs/user_doc/vic_vsphere_admin/vic_cert_reqs.md 

The VCH to Management Portal says "vSphere Integrated Container Management Portal requires _VCH client certificate_ to add a VCH to a project."

Saying VCH client certificate is seems confusing to me since in that connection the VCH is not taking the role of client when adding the VCH. I prefer the diagram to just say "client certificate" or even better "client authentication certificate". 

Calling the client certificate "VCH client certificate" would suggest the certificate comes from the VCH or have the VCH IP and FQDN used for creating the certificate which would not work.  The VIC Appliance, which is the client, to the VCH which would be acting as the server. Same with the docker-client to VCH connection "Docker client requires _VCH client certificate_ to connect to VCH". 

Some where in the documents will need the requirements for acceptable client certificates needs to be outlined. I.e for the VCH to trust the CA that signed the client certificate, the client device FQDN in the subject or subject alternative name and the proper key usage in the v3 extensions that match the key usage chosen for the VCH. Normally key agreement or key encipherment. Both work and and the one used should match with the same key usage the certificate the VCH is currently configured with. I suspect there might be a few more requirements for the client certificate as well. 

The connection between Docker-Client and the registry does not look correct. I have never needed this before and pretty sure it does not happen. I am suspecting that Docker-Client is being confused with Docker-Engine here.

**Comment by stuclem** [comment]
Thanks, @dbarkelew, I'll try to address all of your comments above one-by-one:

1. @dbarkelew: "Not only does deployment need to be looked at but certificate replacement after deployment will need to be looked at. Is there confirmation of what the expected behavior should be."

I would assume that post-deployment, one would have to follow the procedure at [Reconfigure the vSphere Integrated Containers Appliance](https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/reconfigure_appliance.html) to edit the vApp settings and upload a new certificate. However, that would just be one cert for the whole appliance. 

![appliance-cert](https://user-images.githubusercontent.com/16718369/44092219-15d7b90e-9fd0-11e8-8bcd-d71f6372693a.png)

There are no options to provide different certs for Registry or MP: 

![appliance-cert2](https://user-images.githubusercontent.com/16718369/44092224-1ae85cf0-9fd0-11e8-8c15-71a0c0d1b83b.png)

2. @dbarkelew: "I am under the impression each service is still considered different and having individual certificates for each is still supported. I seem to remember that the last certificate replacement I did only updated the certificate the Admiral service used."

Are you talking about updating individual certs by SSH'ing into the appliance and doing it manually? I very much doubt that we support that. @zjs, can you please confirm?

**Comment by stuclem** [comment]
@dbarkelew, regarding the diagram. Yes, I think that we should include this in the docs. If it helps me to understand how the certs all work, it'll help customers.

To address your individual comments in https://github.com/vmware/vic-product/issues/1828#issuecomment-412700334: 

- Changed "vSphere Integrated Container Management Portal requires VCH client certificate to add a VCH to a project" to: 
    - "vSphere Integrated Containers Management Portal uses a client certificate to authenticate with the VCH when you add it to a project".
- Likewise, changed "Docker client requires VCH client certificate to connect to VCH" to: 
   - "Docker client uses a client certificate to authenticate connections to the VCH".

For these two bullets, my initial wording about the MP and the Docker client _requiring_ the VCH client cert came about due to my habit of using the `vic-machine` options to auto-generate client certs. I see how that wording was wrong for custom certs (and not ideal for auto-generated ones either).

For the client requirements, yes, this information is sadly lacking, but I'll be adding it in the context of my general reorg of the certs docs. I'll push an update to the PR in the next day or two.

**Comment by stuclem** [comment]
@zjs, I had an offline conversation with @dbarkelew and he remains convinced that, even though the OVA wizard only allows you to configure/change one certificate, behind the scenes 3 separate certificates are still in use for the different components (presumably duplicates of the one you configure in the deployment wizard). According to @dbarkelew, if you change one certificate, you have to change all of them, manually. Can you please confirm?

**Comment by stuclem** [comment]
Comment from @lcastellano via email:

**Client Certificates**
I would have different sections/pictures for Client and Server certificates. In VIC, client certificates are only used to authenticate the DOCKER api client that talks to the VCH (or to the Docker daemon in case of DCH). That can either be the Docker CLI, the Management Portal or any application using the Docker API. If the VCH is created with the self-signed certificate option, the vic-machine command generates a CA, client certificates and server certificates. Both client and server certificates are signed by the same CA (a choice motivated by terseness .., it doesn’t have to be that way). The VCH acts as a server and validates the incoming client certificate. Part of the validation is to verify the CA that signed it. The VCH uses its self generated CA or the one that was passed in when vic-machine created the VCH. The client (Docker CLI, Management Portal, others ..) must have access to the private key that was used to create the client certificate.

**Registry Server Certificates**
I would suggest to have a different section about Registry Server Certificates. Those are special certificates that apply to all the secure Docker Registries. They are used by the VCH and by the Docker server to authenticate a Registry. Part of the validation is verification of the CA signature. In case of Harbor the certificate may be self signed, meaning that the CA was generated during Vic Appliance installation.

**Comment by stuclem** [comment]
Reopening, as even though https://github.com/vmware/vic-product/pull/1918 is merged, not all of the comments in this issue or in the PR have been fully addressed yet.

**Comment by stuclem** [comment]
Merged in https://github.com/vmware/vic-product/pull/2306
