### ISSUE TITLE
Unable to take snapshot of VIC 1.4.1 which was upgraded from 1.3.1, as the disks which got moved are marked as independent

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1885]
@zjs @hickeng @renmaosheng 

Steps:

1. VIC OVA 1.4.1 was successfully upgraded from 1.3.1 few weeks ago
2. Attempted to take a snapshot on 1.4.1 and the operation failed due to Hard Disk 2, 3 and 4 being marked as independent disks.
![image](https://user-images.githubusercontent.com/25006749/42924768-4e00c7f8-8b49-11e8-9657-10e0d9e111b6.png)

Upgrade from 1.3.1 to 1.4.1 was done using upgrade.sh and following steps https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/upgrade_appliance_manual.html
(disks were not manually moved)
[upgrade.log](https://github.com/vmware/vic-product/files/2208566/upgrade.log)

**Comment by zjs** [comment]
@andrewtchin, was this considered as a part of the design for the new automated upgrade process? A quick search of GitHub didn't show anything, but I wanted to confirm I'm not missing something obvious before digging into this more deeply.

**Comment by andrewtchin** [comment]
This was not considered in upgrade design

**Comment by wjun** [comment]
The strange thing is the upgraded disk with 'independent' mode is read only and cannot be changed to other modes.

**Comment by zjs** [comment]
It's not clear why the disk mode changes to independent. [KB 1007532](https://kb.vmware.com/s/article/1007532) provides instructions for changing the mode back to dependent, which requires that the VM is powered off. However, for some people the UI still shows the mode as read-only (e.g., as noted in  https://github.com/vmware/vic-product/issues/1885#issuecomment-406509109). A work-around for this seems to be to use the VIM API to initiate the change instead of the vCenter UI. This can be achieved using [`govc vm.disk.change -mode persistent`](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#vmdiskchange).

**Comment by zjs** [comment]
It seems like the the `govc vm.disk.attach` command used to attach the copied disks to the new OVA infers the disk mode from the supplied `-link` (default: true) and `-persist` (default: false) arguments.

https://github.com/vmware/govmomi/blob/8d973c31513ae5f16bdcf5d88c1b8ae2267bc63d/govc/vm/disk/attach.go#L105-L120


When we call `govc vm.disk.attach`, we provide neither argument:

https://github.com/vmware/vic-product/blob/e811e0afa23a2302f46a94b6b3b422918700ca28/installer/build/scripts/upgrade/upgrade.sh#L391-L395

Perhaps supplying `-link=false` will fix this.

**Comment by zjs** [comment]
Adding `kind/note` as it seems like we'll need a release note (or perhaps KB?) to provide a work-around to users of 1.4.0 and 1.4.1.
