### ISSUE TITLE
Documented instructions for installing the Client Plug-Ins include incorrect bundle version number for 1.4.1 and 1.4.2

### ISSUE THREAD

**Issue by zjs** [vmware/vic-product#1967]
The [documented instructions](https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/plugins_vcsa.html) for installing the Client Plug-Ins on a vCenter Server Appliance explicitly state `export VIC_BUNDLE=vic_v1.4.0.tar.gz`. This isn't accurate for releases after 1.4.0.

For product release 1.4.1 and 1.4.2, the correct value is `export VIC_BUNDLE=vic_v1.4.1.tar.gz`.

bug2185982

**Comment by zjs** [comment]
@renmaosheng pointed out that we do have a paragraph that addresses this:

> If you have installed a different version of the appliance, update 1.4.0 to the appropriate version in the command above. You can see the correct version by going to https://vic_appliance_address:9443/files/ in a browser. If the vSphere Integrated Containers appliance was configured to expose the file server on a different port, replace 9443 with the appropriate port.

Given this, I'm lowering the severity, but leaving this open; I think the documentation is technically correct, but it seems like at least three readers (the customer, @dbarkelew, and me) initially missed the paragraph, so there may be room for improvement.

**Comment by stuclem** [comment]
@zjs and @renmaosheng, we previously included `export VIC_BUNDLE=vic_v1.4.x.tar.gz` in the docs, and instructed people to update `x` to whatever minor version they were installing. But, people were also missing this instruction. The point of setting the variables was to make the commands completely cuttable and pastable. I will update this to include a table that includes both 1.4.0 and 1.4.1. For 1.4.3 this is unnecessary, because of the automatic installer.
