### ISSUE TITLE
Improve text for Upgrade Appliance regards Initialization

### ISSUE THREAD

**Issue by KeithRichardLee** [vmware/vic-product#2099]
I believe the text regards Initialization is confusing for the reader in the Upgrade Appliance document found here...
https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/upgrade_appliance.html

Excerpt of text... 
_Power on the new version of the vSphere Integrated Containers appliance and wait for it to initialize. Initialization can take a few minutes._

_IMPORTANT: After the new appliance has initialized, do not go to the appliance welcome page of the appliance. Logging in to the appliance welcome page for the first time initializes the appliance. Initialization is only applicable to new installations and causes upgraded appliances not to function correctly._

The instructions inform to wait for the appliance to initialize after power on but then say to not go to the appliance welcome page as logging in will initialize the appliance!!

**Comment by stuclem** [comment]
@KeithRichardLee yes indeed. The problem is that we have unfortunate messaging in the OVA deployment itself. Just after you power on the appliance, if you go to the appliance IP address in a browser, you see a message along the lines of "VIC Appliance is initializing, please wait...".

Then, once that step is complete, the screen in which you enter the VC/PSC details is entitled "Initialize the VIC Appliance", or something similar (I need to check the exact wording). 

@renmaosheng @zjs can we look at the terminology here and come up with different terms for the two stages? Thanks!

**Comment by stuclem** [comment]
I think that the upgrade script also uses "initializing" during the boot phase of the appliance.

**Comment by stuclem** [comment]
Actually, the screen that pops up after appliance initialization says "Complete VIC appliance installation". So, this is indeed a doc problem, not a problem with the implementation itself.
