### ISSUE TITLE
 Support Nimbus location switch from parameter. wdc and sc

### ISSUE THREAD

**Issue by renmaosheng** [vmware/vic-product#2112]
**User Statement:**
Based on the experience of 1.4.3 release, we found every Tuesday and Thursday, we hit the overall quota exceeding issue while using the sc resources, it is better to have a way of switching to wdc during the release time. 
**Details:**

**Acceptance Criteria:**
Avoid the resource limitation issue  to running the nightly tests during release time frame.

**Comment by luwang-vmware** [comment]
I checked with nimbus team about whether there is a cmdline to check the nimbus resource before we launch the pabot scripts. Unluckily the answer is that the only way of knowing each nimbus location resource left is to launch the nimbus-** deploy related cmd.

Ideally implementation method is to add retry mechnasim in the robot resource scripts(Nimbus-Util.robot) to try different nimbus location if we hit out of resource issue. After reading the cases code, we can not implement it in short time, due to some cases are using async mode to deploy several ESXi and we may hit other unexpected test issue when the tested ESXi deployed in different location.

In shortime, based on the info above, what we can do is as following 
1.  add a parameter in the jenkins job(vic-master-scenario) to assign the nimbus location if user knows which nimbus location the testing will use. 
2.  If user does not fill in nimbus location parameter,  Jenkins job(vic-master-scenario) shell scripts dynamcaily assign location parameter according to the rules as below.
     1) if the testenv is 6.5 or 6.0 release, direclty set nimbus location as sc 
     2) if the testenv is 6.7 release, if the trigger day is Tuesday and Thursday, direclty set nimbus location as wdc. Otherwise set as sc.
3.  Edit the Jenkins job(vic-master-scenario) shell scripts to pass through nimbus location parameter
4.  Also need to udpate vic-tools/jenkins/jobs/vic-scenario/build.sh to pass through --variable NIMBUS_LOCATION***

Thanks,
Lu

**Comment by luwang-vmware** [comment]
We have  finished NIMBUS_LOCATION change for VIC. We will implement it in vic-product in Sprint 40.
