### ISSUE TITLE
Registry config error

### ISSUE THREAD

**Issue by grekier** [vmware/vic-product#2120]
Bug Report Basic Information
----------------------------

REQUIRED:

- vCenter Server version: 6.7.0
- Embedded or external PSC: embedded
- How was the OVA deployed? (Flex client, HTML5 client, ovftool): Flex client
- Does the VIC appliance recieve configuration by DHCP? Yes
- VIC 1.4

VIC is up and running and I can perform all operations I wished up till now.
I have issue when trying to register my private docker registry. The error occurs both in global registry and project registry.
After adding the URL for the registry, the validation fails but I can see that the checks are performed towards a URL missing the path after the hostname.
The URL is https://nexus.osnode.com/repository/docker/
and I get the following error
<img width="918" alt="screenshot 2018-10-16 at 15 36 20" src="https://user-images.githubusercontent.com/1302016/47020351-77fa7f80-d159-11e8-98a2-a7f06ed5cf4c.png">

However, if I go to what I expect the URL should be, it works fine as shown in next screenshot
<img width="603" alt="screenshot 2018-10-16 at 15 36 47" src="https://user-images.githubusercontent.com/1302016/47020402-93fe2100-d159-11e8-9029-d131fd288520.png">
From what I can see, the verification strips the path after URL. Is it something I am doing wrong?

**Comment by mshipkovenski** [comment]
Hi @grekier, I have identified the problem. Before addressing the issue can you confirm that you are able to pull any image from this registry via `docker pull nexus.osnode.com/repository/docker/<myimage>`? Thanks.

**Comment by vchrisst** [comment]
Hi @mshipkovenski , I have an identical issue with a Docker Enterprise Registry. When I try to add the registry, I got the following message:
Operation for registry https://my.reg.test:443 failed: Ping attempts failed with errors: Service https://my.reg.test:443/v1/_ping returned error 404 for GET. id 52712060 -- Service https://my.reg.test:443/v2/_catalog?n=1 returned error 401 for GET. id 52712063
The certificate was imported, User is ok and I can login directly from a docker client with the credentials. Also, I can access the Websites which are stated in the error message.
I can reproduce the error with VIC 1.4.3 and 1.4.4.

**Comment by mshipkovenski** [comment]
Hi @vchrisst , your problem seems quite different. You get an error 401 which translates to "Not Authorized". 
1. Did you supply the credentials when you configured the registry in Admiral?
2. Is https://my.reg.test:443 the full address of your registry?

**Comment by vchrisst** [comment]
> 
> 
> Hi @vchrisst , your problem seems quite different. You get an error 401 which translates to "Not Authorized".
> 
>     1. Did you supply the credentials when you configured the registry in Admiral?
> 
>     2. Is https://my.reg.test:443 the full address of your registry?

Hi @mshipkovenski,

I provided the credentials yes. Also the FQDN is correct. It doesn't make a difference if a use a full path (for example https://my.reg.test:443/vchrisst/) or only the FQDN of the registry.

**Comment by mshipkovenski** [comment]
According to the [NXRM3 documentation](https://support.sonatype.com/hc/en-us/articles/115013153887-Docker-Repository-Configuration-and-Client-Connection) "When you make a request using the Docker client, you provide a hostname and port **followed by the Docker image**. Docker **DOES NOT** support the use of a context to specify the path to the repository."

Registries like JFrog Artifactory or Nexus Repository Manager expose repositories on the `/artifactory` or `/repository` endpoint which creates problems for Docker clients trying to push/pull images to them. The problem for Docker is how to distinguish between the path segment and the namespace/repo name, e.g. `hostname:port/path/to/registry/namespace/repo:tag`.

To overcome this limitation Artifactory and NXRM recommend the use of reverse proxies or the so called "repository connectors" to expose registry endpoints. A reverse proxy can rewrite paths, for example `/path/to/registry` to `/`, so that Docker clients can work with them. The [Artifactory documentation](https://www.jfrog.com/confluence/display/RTF/Configuring+a+Reverse+Proxy#ConfiguringaReverseProxy-DockerReverseProxySettings) describes the necessary steps to configure a reverse proxy.

**Comment by renmaosheng** [comment]
@grekier is above method working? I will close the issue if there is no further questions.

**Comment by renmaosheng** [comment]
@grekier please reopen if you still have issues. thanks.

**Comment by grekier** [comment]
@renmaosheng Just to confirm that the above method works for me as well. Sorry about the late response.
