### ISSUE TITLE
Going to https://vic_appliance_address redirects you to a Harbor log in page

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#2216]
#### Summary

After deploying and initializing the appliance, if you enter https://vic_appliance_address in a browser you are sent to https://vic_appliance_address/harbor/sign-in :

![harborlogin.png](https://images.zenhubusercontent.com/56afa3216caf56c9d38c1ecf/85804bf9-82c4-45e0-9682-aadca149738a)

Neither the vSphere Admin credentials nor the VIC appliance root password work on this page.

Entering the VIC Appliance address specifying HTTPS and no port (e.g. https://vic_appliance_address) used to redirect you to the Management Portal login at https://vic_appliance_address:8282. 

Other behaviour is unchanged from previous releases, i.e. entering the VIC Appliance address specifying HTTP or specifying neither HTTP nor HTTPS (e.g. http://vic_appliance_address or just vic_appliance_address) redirects you to the Getting Started page.

#### Expected Behaviour

Specifying HTTPS and no port should send you to the Management Portal login or Getting Started Page. 

#### Details
OVA Build vic-v1.5.0-dev1-6537-4fc79f4b.ova

See also https://github.com/vmware/vic-product/issues/864

**Comment by wy65701436** [comment]
We got the root cause of this issue, it's caused by the changes of Harbor on v1.7.0

[Backgroud]
Harbor redirects all the request to admiral endpoint in the source code, see the details at
https://github.com/goharbor/harbor/blob/985b570bdc371f010b030c3816e6e208ff9718e4/src/ui/controllers/index.go#L30

We do not update the code in v1.7.0 but update the configuration of Nginx because of introducing a new component. We separated the harbor-ui into harbor-portal and harbor-core, and the harbor-portal is responsible for serving the harbor website.

[Root Cause]
As the new component introduced, the request that path to "/" will be proxy to "/portal", and harbor-portal handler the request to launch harbor website, that's why you get the page like the screenshot. 

In the previous release, the request that path to "/" will be proxy to "/ui", and harbor-ui redirects the request to admiral endpoint.(see the above code.)

PS: the admiral endpoint in harbor.cfg is configured like https://12.34.56.78:8282

[Solution]
Update the rule for requestion path to "/", it works on my environment.

**Origin settings:**
```
location / {
      proxy_pass http://ui/;
      ...
}

```
**Updated settings**
```
location / {
      return 302 https://$host:8282$request_uri;
     ...
}
```

But, this should be done on the phase of building VIC ova, you need to write a piece of code to handle this.

**Comment by zhoumeina** [comment]
@DanielXiao , file path: /harbor/make/common/templates/nginx/nginx.https.conf

**Comment by zhoumeina** [comment]
Still, I think we modified the harbor source code is not a elegant way. It should be something can be config.
