### ISSUE TITLE
VIC appliance VM IP can not show in the vm summary page for the vsphere7.0

### ISSUE THREAD

**Issue by ading007** [vmware/vic-product#2541]
Deploy vic appliance using https://storage.googleapis.com/vic-product-ova-releases/vic-v1.5.4-7589-e70af4fe.ova, can get ip normally, but can not show in the vm summary page, as follows:
VC_build: 15610183
esx_build: 15525992

![image](https://user-images.githubusercontent.com/19757922/74303843-2508fa80-4d96-11ea-81ce-7bfab8c65f55.png)

Deploy VM using other .ova file can show ip normally, for example:
http://sc-dbc1218.eng.vmware.com/yifengx/ovf/systest/dhcp-server/systest-dns-dhcp-server_01.ova

**Comment by DanielXiao** [comment]
We use [https://github.com/vmware/govmomi/tree/master/toolbox](toolbox) as guest tool. How can we pin it to the latest version? @wjun

**Comment by dougm** [comment]
It works as expected for me with build number 33262262 using https://github.com/vmware/govmomi/tree/master/toolbox#testing

Seems the UI difference is newer vCenter uses the VirtualMachine `guest.net` property here, but older vCenter UI used the `guest.ipAddress` field + `guest.net`.  The toolbox populates both fields, however `guest.net` requires a fork of the xdr package: https://github.com/vmware/vic/pull/4057

It looks like the `vic-product` repo does not use the same vendored package as vic. Fixing that should  fix the issue here.  In other words, these two directories should have the same contents:
```console
diff -ur vic/vendor/github.com/davecgh/go-xdr vic-product/installer/vendor/github.com/davecgh/go-xdr
```
