### ISSUE TITLE
vSphere Admin documentation is sprinkled with general shell advice about wrapping arguments with quotes

### ISSUE THREAD

**Issue by zjs** [vmware/vic-product#422]
There are numerous (30+) notes in the documentation along the lines of "Wrap any option arguments that include spaces or special characters in quotes" or "Wrap the password in single quotes (') on Mac OS and Linux and in double quotes (") on Windows if it includes special characters."

In some cases, this leads to example commands being repeated three separate times (to show proper use of quotes on each of the three supported operating systems).

Telling users how to use their shell seems out of scope for this document, but if it's content we want to include, I think it would make much more sense to mention once, in a general "How to invoke vic-machine" section (perhaps where we first introduce the idea of having three separate binaries we collectively refer to as `vic-machine`).

Unnecessary repetition of information like this decreases the signal-to-noise ratio in the document.

**Comment by stuclem** [comment]
@zjs I included this everywhere because the first customers to use early versions of VIC kept on stumbling over this very problem. I agree that it the current proliferation of advice is overkill, though, and can definitely be streamlined, perhaps not in a separate topic, but more likely in a single note at the start of any topic that talks about `vic-machine`.

**Comment by zjs** [comment]
Sounds good to me.
