### ISSUE TITLE
Document support for container VM port forwarding

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#502]
@stuclem commented on [Tue May 31 2016](https://github.com/vmware/vic/issues/868)

Per https://github.com/vmware/vic/issues/692.

---

@stuclem commented on [Tue Jul 26 2016](https://github.com/vmware/vic/issues/868#issuecomment-235261573)

This definitely needs to go into the topic on container use. It might require something in admin too.

---

@stuclem commented on [Thu Sep 29 2016](https://github.com/vmware/vic/issues/868#issuecomment-250472214)

https://github.com/vmware/vic/issues/692 is in the icebox.

---

@stuclem commented on [Wed Dec 14 2016](https://github.com/vmware/vic/issues/868#issuecomment-267077036)

https://github.com/vmware/vic/issues/692  is still in the Icebox with no milestone, so leaving this doc issue in icebox too.

**Comment by stuclem** [comment]
Doesn't look like this is in 1.3.

**Comment by stuclem** [comment]
Requested more info from @hickeng in https://github.com/vmware/vic/issues/692

**Comment by hickeng** [comment]
@stuclem This is functional (and has been since 1.3.0) - basically you are able to forward a port within a cVM, in the same way you can via endpoint NAT.

E.g.
`docker run --net=published-container-net -p 80:8080 -d tomcat:alpine`

The above would allow you to access the tomcat webserver via port `80` on the cVM, via `published-container-net` instead of being fixed to port `8080` as defined in the tomcat Dockerfile. This is intended to make it significantly simpler for people to expose services directly via container networks without needing to modify images.

**Comment by stuclem** [comment]
Fixed in https://github.com/vmware/vic-product/pull/2252
