### ISSUE TITLE
Initialize VIC Appliance button in Getting Started breaks Management Portal

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#586]
In the most recent builds of the OVA (`chin-vic-3b4b61e8-upgrade.ova`), there is a new **INITIALIZE VIC APPLIANCE** button on the Getting Started page.

If you successfully deploy the OVA and finalize the installation by logging into VC, you can access the Management Portal without problems. However, as described in https://github.com/vmware/vic-product/issues/483, multiple log-ins cause Management Portal not to load. So, if you click the **INITIALIZE VIC APPLIANCE** button after you have already logged in, Management Portal no longer works.

**Comment by anchal-agrawal** [comment]
/cc @sergiosagu Seeing this issue on a build from the latest release branch (a few commits ahead of RC1): https://storage.googleapis.com/vic-product-ova-builds/vic-eebab0ba-dev.ova

After the PSC `register` command runs once and the Admiral starts, the Admiral UI loads just fine. Upon pressing the `re-initialize appliance` button (which runs the PSC `register` command), the Admiral UI still loads fine **in the same browser session**. If I attempt to load the UI in a different browser session, the UI leads to a blank screen with the URL of the form
```
https://sc-rdops-vm09-dhcp-0-240.eng.vmware.com/websso/SAML2/SSO/vsphere.local?SAMLRequest=zVTfb9owEP5XIr8nTgylwQIqVlatUruyJpumvUzGOcBSYmc%2Bk9D%2Ffk6AFVVVxeMe%2FGLffff9OHlys6%2FKoAGLyugpSaKYBKClKZTeTMn3%2FC5Myc1sgqIqaz7fua1%2Bhj87QBf4Po28f5iSndXcCFTItagAuZM8mz8%2BcBbFvLbGGWlKEix8n9LC9aO2ztXIKUUZ2sLUGDZVPA6LrazDOGTDOAK9iZqqFRYiaSrawgrR0A6W0Sx7og3WW%2FCPpZHCg98ZK6FnOCVrUSKQ4H4xJb9XsLoq0vEVS9LrVELMimFaiNE4lemIFeuxL8OlQFQNvDYi7uBeoxPaTQmLk%2BswTkOW5izmbMAHLEqGo18kWB6lfVL6YNhHPqwORci%2F5PkyXD5leQ%2FQqALsV1%2Ft3Y%2BjZORPh5%2BkPGUpI8GPUzYeg5yS6AnayzPw%2BsB2vpPZyfd3htEO6WR0BU4UwokJPR95IMBq3jG%2BXyxNqeTLGQ928TLMy9K0txaE88qd3UEfYSXcxwDdjSrCdV%2FK684cdKAdCbJlx%2BnbTpRqrcC%2BbtilSgk9quO3xkfV2YXn0i62%2BC3KEaTxLQdWntTZZqPcQiWQCuds2ANTv3KMxkP6ee%2B1dfEjOYLsUf3DaNs2ageRsRvfECf05%2BND1mOFqt9d6T319dy91N7jbjx%2FBg2tWJWQ%2B7t3BP9HVBdQwuacKn0bzuy0m%2Bcf0%2Bwv&RelayState=SessionId&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=CMckPRLzujiyDFwn8cPqGcLPs%2Bjx1LjmAKxBpiKQDP47YV50ezAyMeLc3inbvEjCdl%2BG5r%2B2a4F9IresfR2uZc9K6ocjizW9JDa3FBaPwaFbpGFrQsO%2B%2B%2Ft%2FR9JtuCy7uJX8tD3pGZNBX98ugoO3bEU7GqE2pyGvbR48FKaz0yrpG7%2BdURuU4cSfl5zRfkQLgAUGqD07%2FZi8D6ZTY1LR7hq0wKOS2pedo33YELaTDh8igeVigWAJ0b2iifYsXwzP8cdbpr9SJHi8pLSKCf8heXoBIkZljXLBykRu6TRUn9MXSXN1mqCTr%2BjRS1EOeNIumgP9jwfDyFKSYd9JMJJdtQ%3D%3D
```

The container logs show this message for the above browser request
```
[489][S][2017-08-28T20:22:49.492Z][22][8282/][exceptionCaught][Listener channel exception: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f20485454502f312e310d0a486f73743a2031302e3136302e3133322e3131383a383238320d0a557067726164652d496e7365637572652d52657175657374733a20310d0a4163636570743a20746578742f68746d6c2c6170706c69636174696f6e2f7868746d6c2b786d6c2c6170706c69636174696f6e2f786d6c3b713d302e392c2a2f2a3b713d302e380d0a557365722d4167656e743a204d6f7a696c6c612f352e3020284d6163696e746f73683b20496e74656c204d6163204f5320582031305f31315f3629204170706c655765624b69742f3630332e332e3820284b48544d4c2c206c696b65204765636b6f292056657273696f6e2f31302e312e32205361666172692f3630332e332e380d0a4163636570742d4c616e67756167653a20656e2d75730d0a4163636570742d456e636f64696e673a20677a69702c206465666c6174650d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a0d0a]
```

In addition, once the browser session where the UI was functioning expires, I get the `Your session has expired, please reload` header in the Admiral UI (as expected). However, if I reload the page, I get a blank page again.

@sergiosagu You mentioned in https://github.com/vmware/vic-product/issues/483#issuecomment-322792081 that multiple PSC registrations can cause this issue. However, we have a `re-initialize appliance` button on the OVA's getting started page so users can perform init tasks if something goes wrong. Can multiple registrations be handled on the PSC/Admiral side? Otherwise, we'll need to disable the `re-initialize appliance` button since this breaks the UI completely.

**Comment by anchal-agrawal** [comment]
I also see the token expiration timeout set to 30 minutes:

<img width="905" alt="admiral-token" src="https://user-images.githubusercontent.com/4361620/29796974-d3e62b04-8c19-11e7-8f53-0a26da9cb25d.png">


@sergiosagu Is this for the PSC token? We've set the `get-token` refresh command to run every hour in the OVA.

**Comment by sergiosagu** [comment]
@stuclem / @anchal-agrawal - I don't know what the re-initialize appliance button is supposed to do in general, and related to Admiral in particular. Is it described anywhere what that button is doing?

@anchal-agrawal - The token expiration timeout of that Configuration screen is something related strictly to Harbor (it's in the Registry tab). Nothing to do with any Admiral session or token.

**Comment by stuclem** [comment]
@sergiosagu @anchal-agrawal I see that the button is now located less prominently at the bottom of the page. That's much better, but it still poses a significant risk of someone pressing it and breaking their UI. 

@anchal-agrawal why do we actually need this button in 1.2? I thought that it was purely for restarting the client plug-ins in 1.3...

**Comment by stuclem** [comment]
Thinking about this a bit more, I think that it's too risky to have this button in the Getting Started page if we can't overcome the issue of multiple logins to PSC. Can we not document how to SSH into the appliance and restart it at the command line? At least this way people won't do it by mistake...

I suppose I need to understand better what the circumstances are in which you would need to reinitialize the appliance.

**Comment by anchal-agrawal** [comment]
@sergiosagu The button performs two tasks, one of which is running the PSC `register` command. So pressing the button and then entering the correct vSphere credentials would cause multiple registrations with PSC, since the first registration would have happened earlier when the user finished the init step on the Getting Started page.

Can we handle multiple PSC registrations, or should we prevent that at all costs since the user risks breaking the UI completely? I see a few possible solutions:

1. Multiple PSC registrations are handled on the PSC command / Admiral side and are a no-op if the previous registration is valid.
2. We show the re-initialize button only if there's a failure during the first init after powering on the OVA.
3. We add logic in the init code on the OVA to skip running the `register` command if the PSC config files (`psc-config.properties`, `psc-config.keystore`) are already present on disk.

**Comment by anchal-agrawal** [comment]
Also pinging @andrewtchin for input.

**Comment by anchal-agrawal** [comment]
I think 3 is the most robust solution here, since we also have the `/register` API where the user can manually preform the re-init tasks (which includes the PSC registration). Checking for the presence of PSC config files seems like a good approach, unless there's a better way to check the validity of the PSC registration. @sergiosagu, what do you think?
