### ISSUE TITLE
OVA disk sizes are incorrect on install

### ISSUE THREAD

**Issue by corrieb** [vmware/vic-product#789]
Seems like the disk sizes in the installer are hard-coded and probably should have been changed when the OVA disk sizes were modified in https://github.com/vmware/vic-product/pull/720.

![screen shot 2017-09-11 at 10 49 36 am](https://user-images.githubusercontent.com/1699842/30289210-48591f0c-96e0-11e7-8c9c-80694d41d379.png)
![screen shot 2017-09-11 at 10 49 10 am](https://user-images.githubusercontent.com/1699842/30289211-4876fa90-96e0-11e7-942f-e6f3767d1726.png)

**Comment by corrieb** [comment]
Medium priority, since we shouldn't be misleading admins as to the impact of installation

**Comment by andrewtchin** [comment]
@corrieb I think the sizes are correct, though the way it is displayed may be misleading. On the bottom screenshot 7.9 GB is correct for thin provisioned because that's how much is consumed out of the 16 GB system disk (data disk starts empty), while the 66 GB thick provisioned is 16 + 50 GB. 
I also verified that the final settings in the `.ovf` are correct as they are updated by ovftool after the build completes
