### ISSUE TITLE
Fix --management-gateway example in doc

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#866]
Per comment from @emeirell via email, the example for --management-gateway is wrong.

Here is the doc example:

----

In the following example, `--management-network-gateway` informs the VCH that it can reach all of the vSphere management endoints that are in the ranges 192.168.3.0-255 and 192.168.128.0-192.168.131.255 by sending packets to the gateway at 192.168.2.1. Ensure that the address ranges that you specify include all of the systems that will connect to this VCH instance. 

<pre>--management-network-gateway 192.168.3.0/24,192.168.128.0/24:192.168.2.1</pre>

-----

Here is @emeirell's comment:

"To me it seems the first two networks are the same /24, so why in the text it shows a bigger range for the second network? Am I missing something ?"

@hmahmood I think that you provided this example. Is emeirell correct? Thanks!

**Comment by emeirell** [comment]
Hi @stuclem , yes it's correct.
On the command, the second range is a /24, which is from 192.168.128.0-192.168.128.255
but the text example shows a range from 192.168.128.0-192.168.131.255...... addresses from 192.168.129.0-192.168.131.255 will not have any route in the routing table.
So, from my point of view.... the text example range is wrong or the command example must specify /22 instead of /24.

**Comment by hmahmood** [comment]
Yes @emeirell is correct. It should be `192.168.128.0-192.168.128.255` not `192.168.128.0-192.168.131.255`.

**Comment by stuclem** [comment]
Fixed in https://github.com/vmware/vic-product/commit/71fcc18a542c9ea82603c9d24a6f397dc94f09a2. @emeirell and @hmahmood can you please confirm that this is OK? Thanks!

**Comment by emeirell** [comment]
Hi @stuclem the information provided by @hmahmood  is correct.

**Comment by hmahmood** [comment]
Looks good @stuclem

**Comment by stuclem** [comment]
Thank you @emeirell and @hmahmood !
